import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  FaRoute, 
  FaPlane, 
  FaHotel, 
  FaMapMarkedAlt, 
  FaRobot, 
  FaGlobe,
  FaStar,
  FaUsers,
  FaShieldAlt,
  FaClock
} from 'react-icons/fa';

const Home = () => {
  const features = [
    {
      icon: FaRobot,
      title: 'AI-Powered Planning',
      description: 'Get personalized trip itineraries generated by advanced AI based on your preferences and interests.'
    },
    {
      icon: FaMapMarkedAlt,
      title: 'Live Location Tracking',
      description: 'Real-time location services with Google Maps integration for seamless navigation.'
    },
    {
      icon: FaHotel,
      title: 'Smart Hotel Booking',
      description: 'Find and book the perfect accommodation with detailed reviews and competitive pricing.'
    },
    {
      icon: FaPlane,
      title: 'Transport Booking',
      description: 'Book flights, trains, buses, and taxis all in one place with instant confirmation.'
    },
    {
      icon: FaGlobe,
      title: 'Global Coverage',
      description: 'Explore destinations worldwide with comprehensive travel information and local insights.'
    },
    {
      icon: FaShieldAlt,
      title: 'Secure & Reliable',
      description: 'Your data is protected with industry-standard security and reliable booking systems.'
    }
  ];

  const stats = [
    { number: '10K+', label: 'Happy Travelers', icon: FaUsers },
    { number: '500+', label: 'Destinations', icon: FaGlobe },
    { number: '4.9', label: 'User Rating', icon: FaStar },
    { number: '24/7', label: 'Support', icon: FaClock }
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-primary-600 via-primary-700 to-accent-600 overflow-hidden">
        <div className="absolute inset-0 bg-hero-pattern opacity-10"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 lg:py-32">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
            >
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6">
                Plan Your Perfect Trip with{' '}
                <span className="text-accent-300">AI</span>
              </h1>
              <p className="text-xl text-primary-100 mb-8">
                Discover the world with intelligent travel planning. Get personalized itineraries, 
                book accommodations, and explore destinations with our AI-powered platform.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link
                  to="/register"
                  className="btn-lg bg-white text-primary-600 hover:bg-gray-100 font-semibold"
                >
                  Get Started Free
                </Link>
                <Link
                  to="/about"
                  className="btn-lg border-2 border-white text-white hover:bg-white hover:text-primary-600 font-semibold"
                >
                  Learn More
                </Link>
              </div>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative"
            >
              <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-8 border border-white/20">
                <div className="text-center">
                  <FaRoute className="h-16 w-16 text-white mx-auto mb-4" />
                  <h3 className="text-xl font-semibold text-white mb-2">
                    AI Trip Planner
                  </h3>
                  <p className="text-primary-100">
                    Your intelligent travel companion
                  </p>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="text-center"
              >
                <stat.icon className="h-8 w-8 text-primary-600 mx-auto mb-2" />
                <div className="text-3xl font-bold text-gray-900 mb-1">{stat.number}</div>
                <div className="text-gray-600">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Why Choose AI Trip Planner?
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Experience the future of travel planning with our comprehensive suite of intelligent features
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="card-hover p-6 text-center"
              >
                <feature.icon className="h-12 w-12 text-primary-600 mx-auto mb-4" />
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-primary-600 to-accent-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Ready to Start Your Journey?
            </h2>
            <p className="text-xl text-primary-100 mb-8 max-w-2xl mx-auto">
              Join thousands of travelers who trust AI Trip Planner for their adventures
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/register"
                className="btn-lg bg-white text-primary-600 hover:bg-gray-100 font-semibold"
              >
                Create Free Account
              </Link>
              <Link
                to="/planner"
                className="btn-lg border-2 border-white text-white hover:bg-white hover:text-primary-600 font-semibold"
              >
                Try Trip Planner
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default Home;
